//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgenciesInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AgenciesInfo()
        {
            this.ProjectProposalPreprations = new HashSet<ProjectProposalPrepration>();
        }
    
        public long AgencyID { get; set; }
        public string Name { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> DistID { get; set; }
        public string OwnerName { get; set; }
        public string EmailID { get; set; }
        public string MobileNo { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public string AlternateMobNo { get; set; }
        public string LandLineNo { get; set; }
        public string GSTIN { get; set; }
        public string PANNo { get; set; }
        public Nullable<int> BankID { get; set; }
        public string BranchName { get; set; }
        public string IFSCCode { get; set; }
        public string AccNo { get; set; }
    
        public virtual BankMaster BankMaster { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual StateMaster StateMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectProposalPrepration> ProjectProposalPreprations { get; set; }
    }
}
