//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommitteeMaster
    {
        public long CommitteeID { get; set; }
        public Nullable<int> CommitteeTypeID { get; set; }
        public string CommitteeName { get; set; }
        public Nullable<int> DesignationID { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<int> CommitteeDesignationId { get; set; }
        public Nullable<int> DistID { get; set; }
    
        public virtual CommitteeTypeMaster CommitteeTypeMaster { get; set; }
        public virtual DesignationMaster DesignationMaster { get; set; }
    }
}
