//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DMFFundCollection
    {
        public long FundCollectionId { get; set; }
        public Nullable<long> LesseeId { get; set; }
        public Nullable<int> YearId { get; set; }
        public Nullable<int> MonthId { get; set; }
        public Nullable<decimal> RoyaltyAmt { get; set; }
        public Nullable<decimal> DMFAmt { get; set; }
        public Nullable<decimal> DepositedDMFAmt { get; set; }
        public Nullable<decimal> RemainingDMFAmt { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string ChallanDoc { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
    }
}
