//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionMaster
    {
        public int InspectionID { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<long> ProjectPreparationID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> FundReleaseID { get; set; }
        public Nullable<int> MileStoneID { get; set; }
        public string InspectionCopy { get; set; }
        public string InspectionImage1 { get; set; }
        public string InspectionImage2 { get; set; }
        public string InspectionImage3 { get; set; }
        public string InspectionImage4 { get; set; }
        public Nullable<System.DateTime> InspectionDate { get; set; }
        public Nullable<int> UtilizationID { get; set; }
        public Nullable<int> InstallmentID { get; set; }
        public string Remark { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> SectorTypeId { get; set; }
    }
}
