//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InspectionCheckListAnswerMaster
    {
        public int InspectionCheckListAnswerID { get; set; }
        public string InspectionAnswer { get; set; }
        public Nullable<int> InspectionQuestionID { get; set; }
        public Nullable<int> SectorTypeId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string InspectionQuestion { get; set; }
    }
}
