//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LesseeOpeningDMFAmt
    {
        public long OpeningDMFAmtId { get; set; }
        public Nullable<long> LesseeId { get; set; }
        public Nullable<decimal> DMFOpeningAmt { get; set; }
        public Nullable<System.DateTime> EffectiveDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> MineralId { get; set; }
        public Nullable<int> DistrictId { get; set; }
    }
}
