//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LesseeMaster
    {
        public long LesseeID { get; set; }
        public Nullable<int> StateID { get; set; }
        public Nullable<int> DistID { get; set; }
        public Nullable<int> TehsilID { get; set; }
        public Nullable<long> VillageID { get; set; }
        public string Areacode { get; set; }
        public string GataNo { get; set; }
        public Nullable<decimal> TotalAreainHect { get; set; }
        public string LeaseID { get; set; }
        public Nullable<int> MinralID { get; set; }
        public string LesseeName { get; set; }
        public string MobNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<decimal> BidRate { get; set; }
        public Nullable<System.DateTime> LeaseFromDate { get; set; }
        public Nullable<System.DateTime> LeaseToDate { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
