//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MineralNameMaster
    {
        public int MineralId { get; set; }
        public string MineralName { get; set; }
        public string MineralCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> MineralTypeId { get; set; }
    }
}
