//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhysicalProgressMaster
    {
        public int PhysicalprogressID { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string ProjectNo { get; set; }
        public Nullable<int> MileStoneID { get; set; }
        public Nullable<int> FundReleaseID { get; set; }
        public Nullable<long> ProjectPreparationID { get; set; }
        public Nullable<System.DateTime> PhysicalProgressDate { get; set; }
        public string Remark { get; set; }
        public string PhysicalProgressCopy { get; set; }
        public string PhysicalPInPer { get; set; }
        public Nullable<decimal> AmountSpend { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Phyicalintsallmentflag { get; set; }
        public string PhysicalProgressImages { get; set; }
        public Nullable<int> ProgressStatus { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> SectorTypeId { get; set; }
    }
}
