//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectProposalPrepration
    {
        public long ProjectPreparationID { get; set; }
        public Nullable<int> SectorID { get; set; }
        public string ProsposalNo { get; set; }
        public Nullable<System.DateTime> ProposalDate { get; set; }
        public string ProposalCopy { get; set; }
        public string ProposedBy { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public string TenderNo { get; set; }
        public Nullable<System.DateTime> TenderDate { get; set; }
        public string WorkOrderNo { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public Nullable<long> AgencyID { get; set; }
        public Nullable<decimal> ProjectCost { get; set; }
        public Nullable<decimal> GSTAndOthers { get; set; }
        public Nullable<decimal> SanctionedProjectCost { get; set; }
        public Nullable<int> ProjectStatusID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> ModifyBy { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DistID { get; set; }
        public Nullable<int> TehsilId { get; set; }
        public Nullable<int> BlockId { get; set; }
        public Nullable<int> VillageId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<int> SectorTypeId { get; set; }
        public Nullable<decimal> WorkLatitude { get; set; }
        public Nullable<decimal> WorkLongitude { get; set; }
        public string ProjectDescription { get; set; }
        public string WorkOrderCopy { get; set; }
    
        public virtual AgenciesInfo AgenciesInfo { get; set; }
        public virtual DistrictMaster DistrictMaster { get; set; }
        public virtual ProjectMaster ProjectMaster { get; set; }
        public virtual ProjectStatusMaster ProjectStatusMaster { get; set; }
        public virtual SectorNameMaster SectorNameMaster { get; set; }
    }
}
