//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectAssessment
    {
        public int AssesmentId { get; set; }
        public Nullable<int> DistrictId { get; set; }
        public Nullable<int> SectorTypeId { get; set; }
        public Nullable<int> SectorId { get; set; }
        public Nullable<int> ProjectPreparationID { get; set; }
        public string ProjectNo { get; set; }
        public string feedBack { get; set; }
        public string Photos { get; set; }
        public Nullable<int> NoOfBeneficiaries { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
