//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectMetting
    {
        public long Id { get; set; }
        public Nullable<int> ProjectId { get; set; }
        public Nullable<int> ProjectPreparationID { get; set; }
        public Nullable<int> DistID { get; set; }
        public string MeetingNo { get; set; }
        public Nullable<System.DateTime> MettingDate { get; set; }
        public string MinutesofMeeting { get; set; }
        public string MinutesofMeetingfile { get; set; }
        public string Memberattendancefile { get; set; }
        public string Approvelletterfile { get; set; }
        public string Memberlist { get; set; }
        public string Status { get; set; }
        public Nullable<int> Stageid { get; set; }
        public Nullable<System.DateTime> Attendancedate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> Createddate { get; set; }
        public Nullable<int> Updatedby { get; set; }
        public Nullable<System.DateTime> Updateddate { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SectorID { get; set; }
        public Nullable<int> SectorTypeId { get; set; }
    }
}
