//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProposalStatusMaster
    {
        public int ProposalStatusId { get; set; }
        public string ProposalStatus { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
