//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public long LoginID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<long> EmployeeID { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> DistID { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
