//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMFProjectFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VillageMaster
    {
        public long VillageId { get; set; }
        public string VillageNameInEnglish { get; set; }
        public string VillageNameInHindi { get; set; }
        public string VillageCode { get; set; }
        public Nullable<int> TehsilId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsChakbandiVillage { get; set; }
        public string MSTCVillageName { get; set; }
    }
}
